Add tab
Hexlet/jsbrowser pull request #11
Opened 2021-07-16 08:43 UTC by Surtt

2021-07-16 09:14 UTC, Surtt commented
Я пока закомментировал тесты, так как они пока вообще не писались

2021-07-16 11:34 UTC, fey commented on .github/workflows/nodejs.yml
> +      #   run: make test
а чего закомментировал?

2021-07-16 15:48 UTC, Surtt commented on .github/workflows/nodejs.yml
> +      #   run: make test
actions падает, так как тестов пока нет

2021-07-16 16:08 UTC, fey commented on .github/workflows/nodejs.yml
> +      #   run: make test
Давай простенький тест сделаем.

2021-07-20 08:47 UTC, frontstall requested changes

2021-07-20 08:47 UTC, frontstall commented on src/components/TabItem.jsx
> +  const isActive = id === currentTabId ? true : null;
давай сделаем false вместо null

2021-07-20 08:47 UTC, frontstall commented on src/components/Tabs.jsx
> +      <Button variant="light" onClick={addNewTab}>+</Button>
надо бы добавить title

2021-07-20 08:47 UTC, frontstall commented on src/slices/tabs.js
> +import _ from 'lodash';
https://tyapk.ru/blog/post/correct-way-to-import-lodash-methods

2021-07-20 18:20 UTC, Surtt commented on src/components/Tabs.jsx
> +      <Button variant="light" onClick={addNewTab}>+</Button>
Для кнопки? Типа всплывающий title "New tab", как при наведении на "+" в хроме?

2021-07-21 07:12 UTC, frontstall commented on src/components/Tabs.jsx
> +      <Button variant="light" onClick={addNewTab}>+</Button>
ну пожалуйста :)

атрибут title сделает кнопку доступной - посмотри, как ведёт себя кнопка + в хроме, например

2021-07-21 11:15 UTC, frontstall approved these changes

2021-07-23 06:41 UTC, merged