Add a feature of tab removing
Hexlet/jsbrowser pull request #16
Opened 2022-01-11 16:12 UTC by Guryanov-Maksim

Add an ability of tab closing to close the issue #9

2022-01-11 16:15 UTC, mokevnin commented
@amshkv

2022-01-12 07:43 UTC, amshkv requested changes
Если замечания про текст и перевод строки не существенны, то вот кастомная верстка сильно портит этот пуллреквест
Давайте все же придерживаться бутстрапа и идти с ним за руку, а не против него
ПыСы: похожая кнопка есть в упражнениях на Хекслете, можно подсмотреть как сделано там, скорее всего не идеально и будет хорошо если вы предложите решение лучше

2022-01-12 07:43 UTC, amshkv commented on src/index.css
> +}
у вас редактор не настроен на добавление отступа в конец документа
скорее всего такое будет постоянно выскакивать, поэтому просто советую поискать в своем редакторе нужные настройки
Если это вскод или что-то похожее то:
`Files: Insert Final Newline` и `Files: Trim Final Newlines`

2022-01-12 07:43 UTC, amshkv commented on src/index.css
> +}
Очень, просто ОЧЕНЬ много кастома
мы тут юзаем бутстрап, чтобы не пришлось работать руками лишний раз, а тут именно эта работа руками и есть
вижу что часть вещей можно переделать через бутстрап, для части вещей можно переиспользовать бутстрап, а для того что бутстрапом сделать нельзя - или не делать, или сделать небольшой кастомный класс или необходимые утилиты

2022-01-12 07:43 UTC, amshkv commented on src/components/TabItem.jsx
> +        <span className="visually-hidden">Закрыть вкладку</span>
Вообще, в проектах, мы стараемся использовать переводы через i18n и не хранить сырые тексты в файлах с кодом.
В данном проекте i18n еще не завезли, а значит придется сделать как есть. Только хочу обратить внимание что по коду такие тексты пока на английском языке, а не на русском, поэтому предложу перевести для консистентности так сказать

2022-01-14 10:27 UTC, Guryanov-Maksim commented on src/index.css
> +}
Включил данную настройку у себя в редакторе. Спасибо!

2022-01-14 10:31 UTC, Guryanov-Maksim commented on src/index.css
> +}
Уменьшил количество кастомных стилей, но все равно осталась парочка. Для кнопки закрытия вкладки взял svg из упражнений на Хекслете вместе с размерами.

2022-01-14 10:36 UTC, Guryanov-Maksim commented on src/components/TabItem.jsx
> +        <span className="visually-hidden">Закрыть вкладку</span>
Перевел текст на английский язык. Когда появится i18n уберу текст из кода. Могу попробовать внедрить i18n, но пока тут текста почти нет, переводить нечего.

2022-01-14 10:37 UTC, amshkv commented on src/index.css
> +}
чуть позже проверю, но скорее всего иконку можно/нужно вынести из DOM в картинку, или вообще заюзать бутстраповскую иконку закрытия

2022-01-14 11:26 UTC, Guryanov-Maksim commented on src/index.css
> +}
Я и не заметил иконку закрытия. Может действительно переделать и ее внедрить?

2022-01-14 11:36 UTC, amshkv commented on src/index.css
> +}
https://getbootstrap.com/docs/5.1/components/close-button/
попробуй

2022-01-14 12:02 UTC, Guryanov-Maksim commented on src/index.css
> +}
Сделал, но все равно остался один кастомный класс.

2022-01-14 15:30 UTC, fey commented on src/components/TabItem.jsx
> +        <span className="visually-hidden">Закрыть вкладку</span>
i18n лучше отдельным ПРом

2022-01-14 15:32 UTC, fey commented on src/index.css
> +.close-tab-button {
Кастомные классы делаем с префиксом `x-`

2022-01-14 16:02 UTC, amshkv commented on src/index.css
> +}
я посмотрел, вроде как сильно лучше не сделаешь, оставляй так, только класс переименуй, как Коля сказал
я бы только жирность поменьше сделал для креста, может `fw-light` или `fw-normal`

2022-01-14 16:09 UTC, Guryanov-Maksim commented on src/components/TabItem.jsx
> +        <span className="visually-hidden">Закрыть вкладку</span>
Понял. Я уже и issue видел по поводу добавления i18n.

2022-01-14 16:23 UTC, Guryanov-Maksim commented on src/index.css
> +.close-tab-button {
Сделал, переименовал класс

2022-01-14 16:24 UTC, Guryanov-Maksim commented on src/index.css
> +}
Замечание по поводу имени класса исправил, размер креста уменьшил.

2022-01-14 17:03 UTC, amshkv commented on src/components/TabItem.jsx
> +        <span className="visually-hidden">Close tab</span>
тебе не кажется что aria-label и Close tab несколько дублируют друг друга?
предлагаю Close tab перенести в `aria-label` и оставить одну строку

2022-01-14 17:18 UTC, Guryanov-Maksim commented on src/components/TabItem.jsx
> +        <span className="visually-hidden">Close tab</span>
Этот момент я упустил. Удалил ненужный текст

2022-01-14 17:33 UTC, amshkv approved these changes
знай стало хорошо, всегда есть что улучшить или придумать, но это уже дальше
большой молодец, спасибо!

2022-01-14 18:06 UTC, merged

2022-01-14 18:26 UTC, Guryanov-Maksim commented
Спасибо большое за обратную связь! Теперь я немного стал умнее.