Init project
Hexlet/jsbrowser pull request #3
Opened 2021-06-18 13:49 UTC by Surtt

2021-06-19 12:42 UTC, fey commented
@frontstall посмотришь? Если ок, можно мержить

2021-06-19 14:34 UTC, frontstall requested changes

2021-06-19 14:34 UTC, frontstall commented on .gitignore
> +/build
А dist, который в eslintignore?

2021-06-19 14:34 UTC, frontstall commented on Makefile
> +.PHONY: test
build ещё

2021-06-19 14:34 UTC, frontstall commented on package.json
> +    "@testing-library/jest-dom": "^5.11.4",
Это дев-зависимости, нет?

2021-06-19 14:34 UTC, frontstall commented on package.json
> +  "eslintConfig": {
Не получится так, что из-за этого конфига eslintconfig не будет работать?

2021-06-19 14:34 UTC, frontstall commented on .eslintrc.yml
> +parser: babel-eslint
Кажется, этот пакет деприкейтед. И его не вижу в установленных.

2021-06-21 07:57 UTC, Surtt commented on Makefile
> +.PHONY: test
Так там есть же build

2021-06-21 08:03 UTC, Surtt commented on package.json
> +    "@testing-library/jest-dom": "^5.11.4",
Рекат при инициализации проекта автоматом их туда устанавливает (в dependencies). В сети не нашел какой-либо внятной информации на этот счет. Поэтому я не уверен насчет дев

2021-06-21 08:04 UTC, Surtt commented on package.json
> +  "eslintConfig": {
Локально проверял, eslintrc нормально отрабатывает

2021-06-21 14:13 UTC, frontstall commented on Makefile
> +.PHONY: test
в .PHONY надо добавить build :)

https://stackoverflow.com/questions/2145590/what-is-the-purpose-of-phony-in-a-makefile

2021-06-21 14:14 UTC, frontstall commented on package.json
> +    "@testing-library/jest-dom": "^5.11.4",
https://github.com/testing-library/jest-dom#installation

2021-06-21 14:16 UTC, frontstall commented on package.json
> +  "eslintConfig": {
https://eslint.org/docs/user-guide/configuring/configuration-files#cascading-and-hierarchy

> If there is an .eslintrc and a package.json file found in the same directory, .eslintrc will take priority and package.json file will not be used.

Нужно что-то одно оставить.

2021-06-21 17:42 UTC, Surtt commented on package.json
> +    "@testing-library/jest-dom": "^5.11.4",
Интересно, почему тогда реакт автоматом ставит в dependencies?!🤔

2021-06-22 15:30 UTC, frontstall commented on package.json
> +    "@testing-library/jest-dom": "^5.11.4",
https://github.com/facebook/create-react-app/issues/10602

2021-06-22 15:40 UTC, frontstall commented on Makefile
> +.PHONY: build
одной строчкой:

```makefile
.PHONY: build test
```

2021-06-24 06:42 UTC, merged